FROM apache/airflow:2.9.1

USER root

# Install Java 17
RUN apt-get update && apt-get install -y openjdk-17-jdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Switch back to airflow user for Python packages
USER airflow

# Install Python dependencies
RUN pip install --no-cache-dir \
    apache-airflow==2.9.1 \
    apache-airflow-providers-apache-spark \
    pyspark \
    pandas \
    minio \
    s3fs \
    psycopg2-binary

# Explicitly set the PATH to include Airflow's executable locations
ENV PATH="/home/airflow/.local/bin:${PATH}"